site_name: PPS - Unidad2 - TareaRA2 - Óscar Polo Fernández
theme:
  name: mkdocs

nav:
  - 1. Índice: index.md
  - 2. Trazado de vulnerabilidad: trazado.md
  - 3. Análisis de vulnerabilidad en máquina vulnerable: analisis.md
  - 4. Comprobación de requisitos de Seguridad de una aplicación: comprobacion.md
  - 5. Reflexión: reflexion.md
  - 6. Reflexión sobre los riesgos de las aplicaciones: reflexion.md
